### ISSUE TITLE
内容与标题栏重叠观感不佳

### ISSUE THREAD

**Issue by cyanray** [Cyenoch/Coolapk-UWP#14]
![QQ截图20211007213910](https://user-images.githubusercontent.com/13616289/136396623-689f3f74-cb53-41e4-9110-a8c866e31b77.png)

这个设计看起来是有意为之，难道灵感来自于 Android 的透明状态栏？

但是 Windows 的标题栏有按钮要点击，有文字要显示，还是不要让内容和标题栏重叠好。

而且 Android 上也少让有文字的内容覆盖到标题栏上的设计。

**Comment by Cyenoch** [comment]
这个问题我有发现，但目前因为在refactor分支忙于重构项目结构所以没去解决他，你可以试试找个好办法解决下
